Azure Cache/POC_CacheDemo/POC_CacheDemo/Models/Model.cs
using System;
using System.Collections.Generic;

namespace POC_CacheDemo.Models
{
    [Serializable]
    public class BookViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class DataViewModel
    {
        public List<BookViewModel> ListBook { get; set; }
    }
}

Azure Cache/POC_CacheDemo/POC_CacheDemo/Controllers/BaseController.cs
using POC_CacheDemo.Services;
using System.Web.Mvc;

namespace POC_CacheDemo.Controllers
{
    public class BaseController : Controller
    {
        protected RedisCacheService RedisCacheService;

        public BaseController()
        {
            RedisCacheService = new RedisCacheService();
        }
    }
}

Azure Cache/POC_CacheDemo/POC_CacheDemo/Controllers/CacheController.cs
using POC_CacheDemo.Models;
using POC_CacheDemo.Services;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace POC_CacheDemo.Controllers
{
    public class CacheController : BaseController
    {
        private DataViewModel ListData;
        private List<BookViewModel> Cart = new List<BookViewModel>();

        public CacheController()
        {
            ListData = new DataViewModel()
            {
                ListBook = new List<BookViewModel>()
                {
                    new BookViewModel() { Id = 1, Name = "Book 1" },
                    new BookViewModel() { Id = 2, Name = "Book 2" },
                    new BookViewModel() { Id = 3, Name = "Book 3" },
                    new BookViewModel() { Id = 4, Name = "Book 4"}
                }
            };
        }

        [HttpPost]
        public ActionResult Index(string userName)
        {
            if (!string.IsNullOrWhiteSpace(userName))
            {
                RedisCacheService.Save("userName", userName);
            }

            ViewBag.UserName = RedisCacheService.Get("userName");

            return View(ListData);
        }

        public ActionResult YourCart()
        {
            var cart = new List<BookViewModel>();
            if (Session["YourCart"] != null)
            {
                cart = StackExchangeRedisExtensions.Deserialize<List<BookViewModel>>((byte[])Session["YourCart"]);
            }

            return View(new DataViewModel() { ListBook = cart });
        }

        [HttpPost]
        public ActionResult AddOrRemoveToCart(int id, bool addToCart)
        {
            try
            {
                if (Session["YourCart"] != null)
                {
                    Cart = StackExchangeRedisExtensions.Deserialize<List<BookViewModel>>((byte[])Session["YourCart"]);
                }

                if (addToCart)
                {
                    var item = Cart.Where(x => x.Id == id).SingleOrDefault();
                    if (item == null)
                    {
                        var book = ListData.ListBook.Where(x => x.Id == id).SingleOrDefault();
                        if (book != null)
                        {
                            Cart.Add(book);
                        }
                    }
                }
                else
                {
                    var book = Cart.Where(x => x.Id == id).SingleOrDefault();
                    Cart.Remove(book);
                }

                Session.Add("YourCart", StackExchangeRedisExtensions.Serialize(Cart));

                return Json(new { result = true });
            }
            catch (Exception e)
            {
                return Json(new { result = false });
            }
        }
    }
}

Azure Cache/POC_CacheDemo/POC_CacheDemo/Controllers/HomeController.cs
using System.Web.Mvc;

namespace POC_CacheDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Cache/Index.cshtml
@{
    @model POC_CacheDemo.Models.DataViewModel
    ViewBag.Title = "Index";
}

<h2>Wellcome to MS Azure Redis Cache </h2>

<hr>

<h4>User name: @ViewBag.UserName</h4>

<hr>

<h4>Data table</h4>

<div class="row">
    <div class="col-xs-8">
        <table class="table table-bordered ">
            <thead>
                <tr class="info">
                    <th class="col-xs-1">Id</th>
                    <th class="col-xs-5">Name</th>
                    <th class="col-xs-1"></th>
                </tr>
            </thead>

            <tbody>
                @for (int i = 0; i < Model.ListBook.Count; i++)
                {
                    <tr>
                        <td>@Model.ListBook[i].Id</td>
                        <td>@Model.ListBook[i].Name</td>
                        <td><a href="javascript:void(0)" onclick="AddOrRemoveToCart('@Model.ListBook[i].Id', true)">Add</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<hr />

<div>
    <form action="@Url.Action("YourCart", "Cache")" method="get">
        <button type="submit" class="btn btn-info">Go to your cart</button>
    </form>
</div>

<script type="text/javascript">
    function AddOrRemoveToCart(bookId, addToCart) {
        $.ajax({
            type: "POST",
            url: '/Cache/AddOrRemoveToCart',
            data: { id: bookId, addToCart: addToCart },
            success: function (data) {
                if (data.result) {
                    alert("Action is successful");
                }
                else {
                    alert("OMG. Error");
                }
            },
            error: function () {
                alert("OMG. Error");
            }
        });
    }
</script>

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Cache/YourCart.cshtml
  `@{
      ViewBag.Title = "YourCart";
    @model POC_CacheDemo.Models.DataViewModel
}

<h2>Your cart</h2>

@{
    if (@Model.ListBook.Count > 0)
    {
        <h4>Number item of your cart: @Model.ListBook.Count</h4>

        <div class="row">
            <div class="col-xs-5">
                <table class="table table-bordered">
                    <thead>
                        <tr class="info">
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @for (int i = 0; i < Model.ListBook.Count; i++)
                        {
                            <tr>
                                <td>@Model.ListBook[i].Name</td>
                                <td><a href="javascript:void(0)" onclick="AddOrRemoveToCart('@Model.ListBook[i].Id', false)">Remove</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    else
    {
        <h4>No have any item in your cart</h4>
    }
}

<div>
    <form action="@Url.Action("Index", "Cache")" me method="post">
        <button type="submit" class="btn btn-info">Back</button>
    </form>
</div>

<script type="text/javascript">
    function AddOrRemoveToCart(bookId, addToCart) {
        $.ajax({
            type: "POST",
            url: '/Cache/AddOrRemoveToCart',
            data: { id: bookId, addToCart: addToCart },
            success: function (data) {
                if (data.result) {
                    alert("Action is successful");

                    if (!addToCart) {
                        location.reload(true);
                    }
                }
                else {
                    alert("OMG. Error");
                }
            },
            error: function () {
                alert("OMG. Error");
            }
        });
    }
</script>

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET and Azure</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

<hr />

@using (Html.BeginForm("Index", "Cache", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("User name")
        @Html.TextBox("userName", null, new { @class = "form-control", @placeholder = "Please input user name" })
    </div>
    <button type="submit" class="btn btn-success">Send user name</button>
}

Azure Cache/POC_CacheDemo/POC_CacheDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>